
create table if not exists public.ai_chat_logs (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    session_uuid uuid not null,
    student_id text not null check (char_length(student_id) between 1 and 50),
    level integer not null check (level between 1 and 3),
    step_id text not null,
    role text not null check (role in ('user', 'assistant', 'system_error')),
    content text not null,
    error_code text not null default '',
    selected_response text not null default '',
    status text not null default 'success'
);

create index if not exists ai_chat_logs_student_id_idx
    on public.ai_chat_logs(student_id);
create index if not exists ai_chat_logs_session_uuid_idx
    on public.ai_chat_logs(session_uuid);
create index if not exists ai_chat_logs_timestamp_idx
    on public.ai_chat_logs(timestamp desc);

alter table public.ai_chat_logs enable row level security;
