create table if not exists public.learning_logs (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    session_uuid uuid not null,
    student_id text not null check (char_length(student_id) between 1 and 50),
    level integer not null check (level between 1 and 3),
    step_id text not null,
    response text not null,
    correct boolean not null,
    error_code text not null default '',
    hint_count integer not null default 0 check (hint_count >= 0),
    attempt_number integer not null default 1 check (attempt_number >= 1)
);

create index if not exists learning_logs_student_id_idx
    on public.learning_logs(student_id);

create index if not exists learning_logs_session_uuid_idx
    on public.learning_logs(session_uuid);

create index if not exists learning_logs_timestamp_idx
    on public.learning_logs(timestamp desc);

alter table public.learning_logs enable row level security;

-- 이 앱은 Streamlit 서버의 service_role_key를 사용하므로
-- 브라우저에 공개되는 anon 정책은 만들지 않습니다.



create table if not exists public.ai_chat_logs (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    session_uuid uuid not null,
    student_id text not null check (char_length(student_id) between 1 and 50),
    level integer not null check (level between 1 and 3),
    step_id text not null,
    role text not null check (role in ('user', 'assistant', 'system_error')),
    content text not null,
    error_code text not null default '',
    selected_response text not null default '',
    status text not null default 'success'
);

create index if not exists ai_chat_logs_student_id_idx
    on public.ai_chat_logs(student_id);
create index if not exists ai_chat_logs_session_uuid_idx
    on public.ai_chat_logs(session_uuid);
create index if not exists ai_chat_logs_timestamp_idx
    on public.ai_chat_logs(timestamp desc);

alter table public.ai_chat_logs enable row level security;
